# coding: utf-8

# flake8: noqa
"""
    Restful booker

    An API for practising your testing skills

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.auth_params import AuthParams
from openapi_client.models.auth_response import AuthResponse
from openapi_client.models.booking import Booking
from openapi_client.models.booking_bookingdates import BookingBookingdates
from openapi_client.models.booking_response import BookingResponse
from openapi_client.models.get_ids_response import GetIdsResponse

