# coding: utf-8

"""
    Restful booker

    An API for practising your testing skills

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class BookingBookingdates(BaseModel):
    """
    BookingBookingdates
    """ # noqa: E501
    checkin: date = Field(description="Date the guest is checking in")
    checkout: date = Field(description="Date the guest is checking out")
    __properties: ClassVar[List[str]] = ["checkin", "checkout"]

    @field_validator('checkin')
    def checkin_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        # Coerce date objects to ISO strings for regex validation
        v = value.isoformat() if isinstance(value, date) else value
        if not re.match(r"^\d{4}-\d{2}-\d{2}$", v):
            raise ValueError(r"must validate the regular expression /^\d{4}-\d{2}-\d{2}$/")
        return value

    @field_validator('checkout')
    def checkout_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        v = value.isoformat() if isinstance(value, date) else value
        if not re.match(r"^\d{4}-\d{2}-\d{2}$", v):
            raise ValueError(r"must validate the regular expression /^\d{4}-\d{2}-\d{2}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BookingBookingdates from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BookingBookingdates from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "checkin": obj.get("checkin"),
            "checkout": obj.get("checkout")
        })
        return _obj


