# coding: utf-8

# flake8: noqa

"""
    Restful booker

    An API for practising your testing skills

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AuthParams",
    "AuthResponse",
    "Booking",
    "BookingBookingdates",
    "BookingResponse",
    "GetIdsResponse",
]

# import apis into sdk package
from openapi_client.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.auth_params import AuthParams as AuthParams
from openapi_client.models.auth_response import AuthResponse as AuthResponse
from openapi_client.models.booking import Booking as Booking
from openapi_client.models.booking_bookingdates import BookingBookingdates as BookingBookingdates
from openapi_client.models.booking_response import BookingResponse as BookingResponse
from openapi_client.models.get_ids_response import GetIdsResponse as GetIdsResponse

