# coding: utf-8

"""
    Restful booker

    An API for practising your testing skills

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import pytest

from openapi_client.api.default_api import DefaultApi
from openapi_client.configuration import Configuration
from openapi_client.api_client import ApiClient
from openapi_client.rest import ApiException

# Generated models (if present)
try:
    from openapi_client.models.auth_params import AuthParams
    from openapi_client.models.booking import Booking
    from openapi_client.models.booking_bookingdates import BookingBookingdates
except Exception:  # pragma: no cover - fall back to dicts if models are not available
    AuthParams = None
    Booking = None
    BookingBookingdates = None

from test.conftest import BASE_URL, get_auth_basic_header


class TestDefaultApi:
    """DefaultApi integration tests against the public Restful-Booker API"""

    @pytest.fixture(autouse=True)
    def setup(self):
        """Setup API client with correct configuration"""
        cfg = Configuration(host=BASE_URL)
        self.client = ApiClient(cfg)
        self.api = DefaultApi(self.client)
        yield
        # Cleanup (tearDown equivalent)
        try:
            self.client.close()
        except Exception:
            pass

    def _status(self, resp, default: int) -> int:
        return getattr(resp, "status", None) or getattr(resp, "status_code", None) or default

    def _data(self, resp):
        return getattr(resp, "data", resp)

    def _token_from(self, resp) -> str:
        # Handles either model or ApiResponse(model)
        obj = resp
        if hasattr(resp, "data"):
            obj = resp.data
        tok = getattr(obj, "token", None)
        if tok:
            return tok
        # Fallback to dict-like
        try:
            return obj.get("token")  # type: ignore[attr-defined]
        except Exception:
            return None

    def _create_booking(self):
        if Booking is not None and BookingBookingdates is not None:
            booking_payload = Booking(
                firstname="John",
                lastname="Doe",
                totalprice=123,
                depositpaid=True,
                bookingdates=BookingBookingdates(checkin="2024-01-10", checkout="2024-01-12"),
                additionalneeds="Breakfast",
            )
        else:
            booking_payload = {
                "firstname": "John",
                "lastname": "Doe",
                "totalprice": 123,
                "depositpaid": True,
                "bookingdates": {"checkin": "2024-01-10", "checkout": "2024-01-12"},
                "additionalneeds": "Breakfast",
            }
        create_resp = self.api.booking_post(booking_payload)
        assert self._status(create_resp, 200) == 200
        create_data = self._data(create_resp)
        booking_id = getattr(create_data, "bookingid", None) or (
            create_data.get("bookingid") if isinstance(create_data, dict) else None
        )
        assert booking_id is not None
        return booking_id

    def _auth_cookie(self):
        body = AuthParams(username="admin", password="password123") if AuthParams else {"username": "admin", "password": "password123"}
        auth_resp = self.api.auth_post(body)
        token = self._token_from(auth_resp)
        assert token
        return {"Cookie": f"token={token}"}

    def _auth_basic(self) -> str:
        """Generate Basic Authentication header using shared helper."""
        return get_auth_basic_header()

    def test_ping_get(self) -> None:
        """Health check should return 201 Created"""
        try:
            resp = self.api.ping_get()
            assert self._status(resp, 201) == 201
        except ApiException as e:
            pytest.fail(f"ping_get raised ApiException: {e}")

    def test_auth_post(self) -> None:
        """Auth should return a non-empty token"""
        try:
            if AuthParams is not None:
                body = AuthParams(username="admin", password="password123")
            else:
                body = {"username": "admin", "password": "password123"}
            resp = self.api.auth_post(body)
            token = self._token_from(resp)
            assert token is not None
            assert isinstance(token, str) and len(token) > 0
        except ApiException as e:
            pytest.fail(f"auth_post raised ApiException: {e}")

    def test_booking_get(self) -> None:
        """Get booking IDs should return HTTP 200"""
        try:
            resp = self.api.booking_get()
            assert self._status(resp, 200) == 200
            data = self._data(resp)
            assert data is not None
        except ApiException as e:
            pytest.fail(f"booking_get raised ApiException: {e}")

    def test_booking_post_get_delete(self) -> None:
        """Create → Get → Delete booking (happy path)"""
        # 1) Auth
        if AuthParams is not None:
            body = AuthParams(username="admin", password="password123")
        else:
            body = {"username": "admin", "password": "password123"}
        auth_resp = self.api.auth_post(body)
        token = self._token_from(auth_resp)
        assert token
        cookie_hdr = {"Cookie": f"token={token}"}

        # 2) Create booking
        if Booking is not None and BookingBookingdates is not None:
            booking_payload = Booking(
                firstname="John",
                lastname="Doe",
                totalprice=123,
                depositpaid=True,
                bookingdates=BookingBookingdates(checkin="2024-01-10", checkout="2024-01-12"),
                additionalneeds="Breakfast",
            )
        else:
            booking_payload = {
                "firstname": "John",
                "lastname": "Doe",
                "totalprice": 123,
                "depositpaid": True,
                "bookingdates": {"checkin": "2024-01-10", "checkout": "2024-01-12"},
                "additionalneeds": "Breakfast",
            }
        create_resp = self.api.booking_post(booking_payload)
        assert self._status(create_resp, 200) == 200
        create_data = self._data(create_resp)
        booking_id = getattr(create_data, "bookingid", None) or (
            create_data.get("bookingid") if isinstance(create_data, dict) else None
        )
        assert booking_id is not None

        # 3) Get booking by id
        get_resp = self.api.booking_id_get(booking_id)
        assert self._status(get_resp, 200) == 200

        # 4) Delete booking by id (requires auth)
        auth_basic = self._auth_basic()
        del_resp = self.api.booking_id_delete(booking_id, auth_basic)
        assert self._status(del_resp, 201) == 201

        # 5) Ensure it is gone (expect 404)
        with pytest.raises(ApiException) as exc_info:
            self.api.booking_id_get(booking_id)
        assert getattr(exc_info.value, "status", None) == 404

    # New individual tests matching generated names
    def test_booking_post(self) -> None:
        self._create_booking()

    def test_booking_id_get(self) -> None:
        booking_id = self._create_booking()
        get_resp = self.api.booking_id_get(booking_id)
        assert self._status(get_resp, 200) == 200

    def test_booking_id_put(self) -> None:
        booking_id = self._create_booking()
        headers = self._auth_cookie()
        auth_basic = self._auth_basic()
        # minimal update payload
        if Booking is not None and BookingBookingdates is not None:
            updated = Booking(
                firstname="Jane",
                lastname="Smith",
                totalprice=200,
                depositpaid=False,
                bookingdates=BookingBookingdates(checkin="2024-02-01", checkout="2024-02-05"),
                additionalneeds="WiFi",
            )
        else:
            updated = {
                "firstname": "Jane",
                "lastname": "Smith",
                "totalprice": 200,
                "depositpaid": False,
                "bookingdates": {"checkin": "2024-02-01", "checkout": "2024-02-05"},
                "additionalneeds": "WiFi",
            }
        put_resp = self.api.booking_id_put(booking_id, auth_basic, updated)
        assert self._status(put_resp, 200) == 200

    def test_booking_id_patch(self) -> None:
        booking_id = self._create_booking()
        headers = self._auth_cookie()
        auth_basic = self._auth_basic()
        # Use full Booking body per spec (generator expects Booking)
        if Booking is not None and BookingBookingdates is not None:
            partial = Booking(
                firstname="Patched",
                lastname="Doe",
                totalprice=123,
                depositpaid=True,
                bookingdates=BookingBookingdates(checkin="2024-01-10", checkout="2024-01-12"),
                additionalneeds="Dinner",
            )
        else:
            partial = {
                "firstname": "Patched",
                "lastname": "Doe",
                "totalprice": 123,
                "depositpaid": True,
                "bookingdates": {"checkin": "2024-01-10", "checkout": "2024-01-12"},
                "additionalneeds": "Dinner",
            }
        patch_resp = self.api.booking_id_patch(booking_id, auth_basic, partial)
        assert self._status(patch_resp, 200) == 200

    def test_booking_id_delete(self) -> None:
        booking_id = self._create_booking()
        headers = self._auth_cookie()
        auth_basic = self._auth_basic()
        del_resp = self.api.booking_id_delete(booking_id, auth_basic)
        assert self._status(del_resp, 201) == 201
